# Generated by Django 5.0.1 on 2024-01-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTraining', '0002_trainingname_trainingimages_name_traininglabel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininglabel',
            name='image',
        ),
        migrations.AddField(
            model_name='traininglabel',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='static/labels/'),
        ),
    ]
