# Generated by Django 5.0.1 on 2024-02-03 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTraining', '0004_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CameraScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=100)),
                ('video_source', models.URLField()),
                ('Cameraname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelTraining.trainingname', to_field='name')),
            ],
        ),
    ]
