# Generated by Django 5.0.1 on 2024-02-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTraining', '0005_alter_camera_name_camerascreen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerascreen',
            name='Cameraname',
        ),
        migrations.RemoveField(
            model_name='camerascreen',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='camerascreen',
            name='video_source',
        ),
        migrations.AddField(
            model_name='camerascreen',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelTraining.camera'),
        ),
        migrations.AddField(
            model_name='camerascreen',
            name='last_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camerascreen',
            name='last_video_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
