# Generated by Django 5.0.1 on 2024-02-16 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTraining', '0006_remove_camerascreen_cameraname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraWarningVideoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('labels', models.CharField(max_length=200)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelTraining.camera')),
            ],
        ),
    ]
