# Generated by Django 5.0.1 on 2024-02-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTraining', '0007_camerawarningvideolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerawarningvideolist',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelTraining.camera'),
        ),
        migrations.AlterField(
            model_name='camerawarningvideolist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
