# Generated by Django 5.0.1 on 2024-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTraining', '0008_camerawarningvideolist_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerawarningvideolist',
            name='video',
            field=models.FileField(upload_to='Warning/videos/'),
        ),
    ]
