# Generated by Django 5.0.1 on 2024-02-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTraining', '0010_camera_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerawarningvideolist',
            name='video',
        ),
        migrations.AddField(
            model_name='camerawarningvideolist',
            name='image',
            field=models.FileField(null=True, upload_to='Warning/images/'),
        ),
    ]
