# Generated by Django 5.0.1 on 2024-02-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTraining', '0011_remove_camerawarningvideolist_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraWarningLabelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelTraining.camera')),
            ],
        ),
    ]
