# Generated by Django 5.0.1 on 2024-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='filename',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/test/images/'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='label',
            field=models.FileField(blank=True, null=True, upload_to='static/test/labels/'),
        ),
    ]
