# Generated by Django 5.0.1 on 2024-02-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0002_remove_imagedata_filename_imagedata_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloads/')),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageData',
        ),
    ]
