# Generated by Django 5.0.1 on 2024-02-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0003_downloadedfile_delete_imagedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
