# Generated by Django 5.0.1 on 2024-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0004_remove_downloadedfile_file_downloadedfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedfile',
            name='file_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
