# Generated by Django 5.0.1 on 2024-02-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0005_alter_downloadedfile_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedfile',
            name='file_path',
        ),
    ]
