# Generated by Django 5.0.1 on 2024-02-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0007_rename_file_name_downloadedfile_dataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedfile',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='project_version',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
