# Generated by Django 5.0.1 on 2024-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0010_runnumberoftests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trained_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trained_model', models.FileField(blank=True, null=True, upload_to='static/labels/')),
            ],
        ),
        migrations.RenameModel(
            old_name='RunNumberOfTests',
            new_name='RunNumberOfTest',
        ),
    ]
