# Generated by Django 5.0.1 on 2024-02-21 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0011_trained_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModelTrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='trained_model',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trained_model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trained_model',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
