# Generated by Django 5.0.1 on 2024-02-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0012_newmodeltrainingstatus_trained_model_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trained_model',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
