# Generated by Django 5.0.1 on 2024-02-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0013_alter_trained_model_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trained_model',
            name='Test_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
